### ISSUE TITLE
bagaimana cara instalasi nya ?

### ISSUE THREAD

**Issue by andridgitalbox** [andriawan/AndDrive#1]
Allo min,
gimana cara nya implementasi kan yah ?
saya cek untuk masukan client id dan api nya belom ketemu
dan untuk cara enable api gdrive nya  bagaimana ?
terima kasih

**Comment by andriawan** [comment]
terima kasih @andrinda atas informasi issue...seputar api google drive client id anda bisa merujuk ke dokumentasi resmi dan web google di https://console.developers.google.com. untuk issue code secara spesific, mohon sertakan detail file/line dari code. Terima kasih

**Comment by andridgitalbox** [comment]
terima kasih om @andriawan mungkin saya newbie dalam hal ini :)
untuk api dan client di sisi laravel dimana yah ?
makasih

**Comment by andriawan** [comment]
@andrinda untuk konfigurasi tersebut. AndDrive memakai file konfigurasi dibawah folder config/services.php dimana valuenya diambil dari file .env. silahkan bisa dicek.

**Comment by andridgitalbox** [comment]
siang om @andriawan saya menemukan error sperti dbwah ini
https://i.imgsafe.org/e9/e987eec3ff.png
apakah setingan api google nya atau dimana nya
terima kasih

**Comment by andriawan** [comment]
@andrinda itu bukan error...itu hasil dump session...bisa dicomment aja code yg menampilkan itu...

**Comment by andridgitalbox** [comment]
Done Min @andriawan but missing vendor nih sperti dibawah ini
<script src="vendor/jquery/v2/jquery-2.1.4.js"></script>
<script src="vendor/bootstrap/v4/js/bootstrap.min.js"></script>

bisa ditambahkan vendor nya min ?terima kasih

**Comment by andriawan** [comment]
Silahkan bisa ditambahkan sendiri untuk keperluan pengembangan local masing2 @andrinda
